language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
  - hhvm

before_script: composer install

install:
  - composer show guzzlehttp/guzzle

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true